# Generated by Django 2.2.1 on 2019-06-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('title', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('contend', models.CharField(max_length=10000)),
                ('time', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('privilege', models.PositiveSmallIntegerField()),
                ('audited', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(max_length=255, upload_to='')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/')),
                ('status', models.CharField(blank=True, choices=[('0', '发布中'), ('1', '未发布')], max_length=1, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=20)),
            ],
        ),
    ]
